### ISSUE TITLE
Change in song results in Javascript-error

### ISSUE THREAD

**Issue by monkeybub** [jeffvli/sonixd#251]
**Describe the bug**
When playing on the client for Ubuntu, the crossfade always results in a Javascript-error.

**To Reproduce**
1. Open the client
2. Play a song
3. Wait for it to end and start another

**Expected behavior**
No error :-)

**Screenshots**
![image](https://user-images.githubusercontent.com/100896757/156702516-4579ab03-6918-4b62-9366-a0cb338e7aec.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 21.10

**Additional context**
N/A

**Comment by jeffvli** [comment]
Hmm.. I don't think I've seen this error before.

Does it disappear when switching to the gapless preset (or anything else)?

**Comment by jee-r** [comment]
hi 

I've similar issue on debian 11 using the last Appimage on my [Gonic](https://github.com/sentriz/gonic) server, even if i switch to gapless mode.

this append when : 
- auto switch to next track when an album/playlist is played
- manualy skip to next track
- seek on a track 


in fact there is two errors  windows :
![screenshot_2022-03-10-12:31:40](https://user-images.githubusercontent.com/10530469/157653792-063deb55-3c22-42fa-9b37-9f4bb8f4eb71.png)
![screenshot_2022-03-10-12:33:00](https://user-images.githubusercontent.com/10530469/157653750-5f27c98e-40e5-499f-a8b0-8f45efd7ec0d.png)

hope this help

**Comment by jee-r** [comment]
i'm using gnome 3.38, maybe it's the [Media Control addon](https://extensions.gnome.org/extension/4470/media-controls/) that block the MPRIS request. I try to disable it but it's don't resolve the issue.

**Comment by mrjovanovic** [comment]
I'm having a similar issue using the latest AppImage (v0.15.2) on Debian 11. Error message as follows:

![image](https://user-images.githubusercontent.com/4664783/177056306-467ab75a-941c-4650-94a6-b743dc5fe9f1.png)

**Comment by jeffvli** [comment]
@mrjovanovic What server are you using? Seems like the song you're trying to play doesn't have a server ID which is causing the error.

**Comment by mrjovanovic** [comment]
Using a self-hosted funkwhale server. Not sure if this is an issue I need to bring upstream or if it's within this app.

**Comment by jeffvli** [comment]
@mrjovanovic I added a fallback for the id check so hopefully that should resolve the error for 0.15.3.

**Comment by mrjovanovic** [comment]
Hm, still getting same error in 0.15.3. Could it be because I'm using the AppImage? Playback functionality is perfect by the way.

**Comment by jeffvli** [comment]
@mrjovanovic Is the error still the same?

**Comment by mrjovanovic** [comment]
Yes, I think so. Here is a screenshot (can't copy/paste the error text for
some reason, sorry).
[image: image.png]
